package termcolor

var ColorNames = [][]string{
	[]string{"black", "css:black"},
	[]string{"dark red 1"},
	[]string{"mixed green 1"},
	[]string{"mixed orange 1"},
	[]string{"mixed blue 1"},
	[]string{"purple 1"},
	[]string{"cyan 1"},
	[]string{"light gray"},
	[]string{"dark gray"},
	[]string{"light red"},
	[]string{"light green"},
	[]string{"yellow"},
	[]string{"light blue"},
	[]string{"light purple"},
	[]string{"light cyan"},
	[]string{"white", "css:white"},
	[]string{"black", "css:black"},
	[]string{"blue 4"},
	[]string{"blue 3", "css:darkblue"},
	[]string{"blue 2"},
	[]string{"blue 1", "css:mediumblue"},
	[]string{"blue", "css:blue"},
	[]string{"green 4", "css:darkgreen"},
	[]string{"blue stone"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"green 3", "css:green"},
	[]string{},
	[]string{"css:darkcyan"},
	[]string{},
	[]string{},
	[]string{},
	[]string{"green 2"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"green 1"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"green", "css:lime"},
	[]string{},
	[]string{"css:springgreen"},
	[]string{},
	[]string{},
	[]string{"cyan", "css:cyan", "css:aqua"},
	[]string{"red 5"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"red 4", "css:darkred"},
	[]string{},
	[]string{"css:darkmagenta"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:olive"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:lightskyblue"},
	[]string{"css:chartreuse"},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:aquamarine"},
	[]string{},
	[]string{"red 3"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"red 2"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:tan"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:lightgray"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:lightcyan"},
	[]string{"red", "css:red"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:fuchsia", "css:magenta"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:darkorange"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:orange"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:gold"},
	[]string{},
	[]string{"css:darkgreen"},
	[]string{"css:navajowhite"},
	[]string{},
	[]string{},
	[]string{"css:yellow"},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:cornsilk"},
	[]string{"white", "css:white"},
	[]string{"gray 23"},
	[]string{"gray 22"},
	[]string{"gray 21"},
	[]string{"gray 20"},
	[]string{"gray 19"},
	[]string{"gray 18"},
	[]string{"gray 17"},
	[]string{"gray 16"},
	[]string{"gray 15"},
	[]string{"gray 14"},
	[]string{"gray 13", "css:dimgray"},
	[]string{"gray 12"},
	[]string{"gray 11", "css:gray", "css:grey"},
	[]string{"gray 10"},
	[]string{"gray 9"},
	[]string{"gray 8"},
	[]string{"gray 7", "css:darkgrey"},
	[]string{"gray 6"},
	[]string{"gray 5", "css:silver"},
	[]string{"gray 4"},
	[]string{"gray 3", "css:lightgray"},
	[]string{"gray 2", "css:gainsboro"},
	[]string{"gray 1"},
	[]string{"gray 0"},
}
