package termcolor

var ColorNames = [][]string{
	[]string{"black"},
	[]string{"dark red 1"},
	[]string{"mixed green 1"},
	[]string{"mixed orange 1"},
	[]string{"mixed blue 1"},
	[]string{"purple 1"},
	[]string{"cyan 1"},
	[]string{"light gray"},
	[]string{"dark gray"},
	[]string{"light red"},
	[]string{"light green"},
	[]string{"yellow"},
	[]string{"light blue"},
	[]string{"light purple"},
	[]string{"light cyan"},
	[]string{"light gray 2"},
	[]string{"black"},
	[]string{"blue 4"},
	[]string{"blue 3"},
	[]string{"blue 2"},
	[]string{"blue 1"},
	[]string{"blue"},
	[]string{"green 4"},
	[]string{"blue stone"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"green 3"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"green 2"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"green 1"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"green"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"red 5"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"red 4"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"red 3"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"red 2"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"red 1"},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{""},
	[]string{"gray 23"},
	[]string{"gray 22"},
	[]string{"gray 21"},
	[]string{"gray 20"},
	[]string{"gray 19"},
	[]string{"gray 18"},
	[]string{"gray 17"},
	[]string{"gray 16"},
	[]string{"gray 15"},
	[]string{"gray 14"},
	[]string{"gray 13"},
	[]string{"gray 12"},
	[]string{"gray 11"},
	[]string{"gray 10"},
	[]string{"gray 9"},
	[]string{"gray 8"},
	[]string{"gray 7"},
	[]string{"gray 6"},
	[]string{"gray 5"},
	[]string{"gray 4"},
	[]string{"gray 3"},
	[]string{"gray 2"},
	[]string{"gray 1"},
	[]string{"white"},
}
