//go:generate go run gen-names.go

package termcolor

var ColorNames = [][]string{
	[]string{"black", "css:black"},
	[]string{"dark red 1", "Heartbeat"},
	[]string{"mixed green 1", "Phosphor Green"},
	[]string{"mixed orange 1", "Tijolo"},
	[]string{"mixed blue 1", "Bohemian Blue"},
	[]string{"purple 1", "Purple Potion"},
	[]string{"cyan 1", "Jade Orchid"},
	[]string{"light gray", "Covered in Platinum"},
	[]string{"dark gray", "Stone Cold Gray"},
	[]string{"light red", "Fluorescent Red"},
	[]string{"light green", "Puyo Blob Green"},
	[]string{"yellow", "Pīlā Yellow"},
	[]string{"light blue", "Shady Neon Blue"},
	[]string{"light purple", "Ultimate Pink"},
	[]string{"light cyan", "Electric Sheep"},
	[]string{"white", "css:white"},
	[]string{"black", "css:black"},
	[]string{"blue 4"},
	[]string{"blue 3", "css:darkblue", "Midnight in Tokyo"},
	[]string{"blue 2"},
	[]string{"blue 1", "css:mediumblue", "Bluealicious"},
	[]string{"blue", "css:blue"},
	[]string{"green 4", "css:darkgreen", "Cucumber", "Pakistan Green"},
	[]string{"blue stone"},
	[]string{"orient"},
	[]string{},
	[]string{},
	[]string{},
	[]string{"green 3", "css:green", "Fine Pine"},
	[]string{"Absinthe Turquoise", "Golf Green", "Chagall Green"},
	[]string{"css:darkcyan", "Green Moblin"},
	[]string{"Stomy Shower"},
	[]string{},
	[]string{"Too Blue to be True"},
	[]string{"green 2"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"green 1"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"green", "css:lime"},
	[]string{},
	[]string{"css:springgreen"},
	[]string{},
	[]string{},
	[]string{"cyan", "css:cyan", "css:aqua"},
	[]string{"red 5", "Spikey Red"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Rhine Castle", "Shades On"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"glade green"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Verdigris Green"},
	[]string{},
	[]string{"tradewind"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"red 4", "css:darkred", "Chanticleer"},
	[]string{},
	[]string{"css:darkmagenta", "Mardi Gras"},
	[]string{"Shade of Violet"},
	[]string{},
	[]string{"electric violet"},
	[]string{"Rat Brown"},
	[]string{"Rabbit Paws"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:olive"},
	[]string{"clay creek"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Island Oasis"},
	[]string{"css:lightskyblue"},
	[]string{"css:chartreuse", "Lasting Lime"},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:aquamarine"},
	[]string{"Glitter Shower"},
	[]string{"red 3", "bright red"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Orange Brown"},
	[]string{"Italian Villa", "Poppy Prose", "Sienna Red"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Clay Ochre", "Roman Coin", "Light Oak Brown"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Palm"},
	[]string{"Lively Ivy", "Wall Green"},
	[]string{"silver chalice", "Smoke Screen"},
	[]string{},
	[]string{},
	[]string{"King Lime"},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Rivers Edge"},
	[]string{},
	[]string{"Lime Acid"},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Mintastic"},
	[]string{"Celeste", "Frostbite", "Italian Sky Blue"},
	[]string{"red 2", "Rosso Corsa", "Hot Fever"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Spiced Coral", "Deep Sea Coral", "Roman"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Peaches of Immortality", "Copperfield"},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Palomino Gold"},
	[]string{"Sell Gold", "Butterscotch Bliss", "Equator"},
	[]string{"css:tan", "Santa Fe Tan", "Calico", "Caramel Cloud"},
	[]string{"Mary Rose"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"Green Mesh"},
	[]string{"gray 3"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"snowy mint"},
	[]string{"css:lightcyan", "Refreshing Primer"},
	[]string{"red", "css:red"},
	[]string{"Flaming Hot Flamingoes"},
	[]string{"Fancy Fuchsia"},
	[]string{"Mean Girls Lipstick"},
	[]string{},
	[]string{"css:fuchsia", "css:magenta"},
	[]string{"Vivid Orange"},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{},
	[]string{"css:darkorange", "Mandarin Jelly"},
	[]string{},
	[]string{"geraldine"},
	[]string{},
	[]string{"Pink Delight"},
	[]string{"Darling Bud"},
	[]string{"css:orange", "Gold Fusion"},
	[]string{"Vintage Orange"},
	[]string{"Spice Pink"},
	[]string{"cornflower lilac"},
	[]string{},
	[]string{},
	[]string{"css:gold"},
	[]string{"dandelion"},
	[]string{"Workout Routine"},
	[]string{"css:navajowhite", "light apricot"},
	[]string{"cosmos"},
	[]string{},
	[]string{"css:yellow"},
	[]string{},
	[]string{"Cinque Foil"},
	[]string{"portafino"},
	[]string{"css:cornsilk", "cumulus"},
	[]string{"white", "css:white"},
	[]string{"gray 24", "cod gray", "Reversed Grey"},
	[]string{"gray 23", "Dark Tone Ink"},
	[]string{"gray 22", "Eerie Black"},
	[]string{"gray 21", "Nero"},
	[]string{"gray 20", "mine shaft"},
	[]string{"gray 19", "Dead Pixel"},
	[]string{"gray 18", "Goshawk Grey"},
	[]string{"gray 17", "Black Oak"},
	[]string{"gray 16", "Shadow Mountain"},
	[]string{"gray 15"},
	[]string{"gray 14", "css:dimgray", "dove gray"},
	[]string{"gray 13", "Steel Wool", "Sonic Silver"},
	[]string{"gray 12", "css:gray", "css:grey"},
	[]string{"gray 11"},
	[]string{"gray 10"},
	[]string{"gray 9"},
	[]string{"gray 8", "css:darkgrey"},
	[]string{"gray 7"},
	[]string{"gray 6", "css:silver", "Dust to Dust"},
	[]string{"gray 5", "Silver Polish"},
	[]string{"gray 4", "css:lightgray", "Ancestral Water"},
	[]string{"gray 2", "css:gainsboro", "alto"},
	[]string{"gray 1", "mercury"},
	[]string{"gray 0", "gallery"},
}
